# Generated by Django 3.2.8 on 2023-01-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_transfer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='player_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_in', to='backend.footballer'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='player_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_out', to='backend.footballer'),
        ),
    ]
