# Generated by Django 3.2.8 on 2023-01-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20230122_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballer',
            name='points',
        ),
        migrations.AddField(
            model_name='myfootballer',
            name='captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myfootballer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myfootballer',
            name='vice_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='powerup',
            name='powerup_type',
            field=models.CharField(choices=[('TC', 'Potrójny kapitan'), ('SC', 'Super Rezerwowi')], max_length=30, null=True),
        ),
    ]
