# Generated by Django 3.2.8 on 2023-01-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230122_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='AvayPlayed',
            field=models.ManyToManyField(blank=True, related_name='awayplayed', to='backend.Footballer'),
        ),
        migrations.AddField(
            model_name='match',
            name='HomePlayed',
            field=models.ManyToManyField(blank=True, related_name='homeplayed', to='backend.Footballer'),
        ),
    ]
