# Generated by Django 3.2.8 on 2023-01-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_matchday_same_team_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfootballer',
            name='footballer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footballer', to='backend.footballer'),
        ),
    ]
